Components/BasketSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookStore.Models;

// Used to define the component view of the shopping cart as an icon

namespace BookStore.Components
{
    public class BasketSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        
        public BasketSummaryViewComponent (Basket basketService)
        {
            basket = basketService;
        }

        public IViewComponentResult Invoke ()
        {
            return View(basket);
        }
    }
}

Components/CategoriesViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }

        public CategoriesViewComponent (IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["Category"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Views/Shared/BookInfoSummary.cshtml
@{
}

@model Book 

@*Creating a partial view that can be reused in different parts of the website*@

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h3>@Model.Title</h3>

        <span class="badge bg-info" style="float:right">
            <li>Author: @Model.Author</li>
        </span>
    </div>

    <ul>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.ISBN</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Page Count: @Model.PageCount</li>
        <li>Price: $@Model.Price</li>
    </ul>

    <form method="post" asp-page="/Purchase">

        <input type="hidden" asp-for="@Model.BookID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        @* As a boostrap demonstration, I added a toggle over the purchase button so it displays a message when hovering over it.*@

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end" data-toggle="tooltip" title="Add this book to your cart">Purchase</button>
        </span>

    </form>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    @*bring in bootstrap and html, set up title*@
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-1 text-right">
                    <vc:basket-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:categories></vc:categories>

        </div>
        @*this is a shared layout, so the body needs to be rendered*@
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
    
    <footer>Seth's Book Store © 2022</footer>
</body>
</html>