Models/Purchase.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
    public class Purchase
    {
        [Key]
        [BindNever]
        public int PurchaseId { get; set; }

        [BindNever]
        public ICollection<BasketLineItem> Lines { get; set; }

        [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter the first address line")]
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }

        [Required(ErrorMessage = "Please enter a city name")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please enter a state")]
        public string State { get; set; }
        public string Zip { get; set; }

        [Required(ErrorMessage = "Please enter a country")]
        public string Country { get; set; }

        public bool Anonymous { get; set; }

        [BindNever]
        public bool Shipped { get; set; }
    }
}

Controllers/PurchaseController.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// We are creating a separate controller to keep things clean

namespace BookStore.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }

        public PurchaseController (IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Purchase.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Infrastructure;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

// Building an instance of the basket and loading it so we can use it

namespace BookStore.Pages
{
    public class PurchaseModel : PageModel
    {
        private IBookStoreRepository repo { get; set; }

        public PurchaseModel (IBookStoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        // Look to see if there is already info for the basket by session, if not create new
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        
        }

        // Load item according to what is selected, then add it to the basket
        // Include info for user session
        public IActionResult OnPost(int BookID, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookID == BookID);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove (int BookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookID == BookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Views/Purchase/Checkout.cshtml
@{
}

@model Purchase

<h2>Check out now</h2>
<p>Please enter your details...</p>

@*This is the model for the customer information that will be entered and used
    at checkout*@

<form method="post" asp-controller="Purchase" asp-action="Checkout">

    <div asp-validation-summary="All" class="text-danger"></div>

    <h4>Ship To</h4>

    <div class="form-group">
        <label asp-for="Name">Name</label><input asp-for="Name" class="form-control" />
    </div>

    <h4>Address</h4>

    <div class="form-group">
        <label asp-for="AddressLine1">Address Line 1:</label>
        <input asp-for="AddressLine1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine2">Address Line 2:</label>
        <input asp-for="AddressLine2" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine3">Address Line 3:</label>
        <input asp-for="AddressLine3" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="City">City:</label>
        <input asp-for="City" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="State">State</label>
        <input asp-for="State" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Zip">Zip:</label>
        <input asp-for="Zip" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Country">Country:</label>
        <input asp-for="Country" class="form-control" />
    </div>

    <div class="checkbox">
        <label>
            <input asp-for="Anonymous" /> Purchase Anonymously
        </label>
    </div>

    <div class="float-end">
        <input class="btn btn-primary" type="submit" value="Complete Purchase" />
    </div>

    @* This is a progress bar to demonstrate booststrap *@
    <br /><br /><br />


    <div class="container">
        <h2>One step closer to receiving your order!</h2>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%">
                <span class="sr-only">75% Complete</span>
            </div>
        </div>
    </div>

</form>